version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Save hello to file"
          command: "echo 'Hello, World!' > output.txt"
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: /tmp/dir
      - run: cat /tmp/dir/output.txt

workflows:
  hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file
