version: 2.1

jobs:
  hello:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  print_env:
    docker:
      - image: alpine:latest
    steps:
      - run: "echo Env var HANS: $HANS"

workflows:
  hello-workflow:
    jobs:
      - hello
